### PR TITLE
BitZeny: Update hard-coded seed nodes

### PR DESCRIPTION
**Pull request by ghost**
Update hard-coded seeds list from observed IP addresses.

### CODE REVIEW

**Comment by hitobb** [comment]
Some Mining pools might change global ip address for solve performance problems.
I think DNSseed is better.

[DNS Seed list(main net)]

seed.bitzeny.jp 
bitzeny.seed.lapool.me

[DNS seed list(test net)]

seed.bitzeny.jp 

[detail]

https://lapool.me/seed/

https://bitzeny.info/d/30-bitzeny/24

**Comment by ghost** [comment]
> Some Mining pools might change global ip address for solve performance problems.

It's no problem if there is at least one connectable node in the list or DNS seed. So, all nodes in the list are no need always online.

> DNS seeds

LA Pool has been added from https://github.com/BitzenyCoreDevelopers/bitzeny/commit/3bc5bf1baddc6cc0a58b3ee87c1a2e64d1542ed9.

**Comment by zenywallet** [comment]
Please use testnet-seed.bitzeny.jp for the testnet.

**Comment by zenywallet** [comment]
I wonder is it enough for the current network...

**Comment by ghost** [comment]
@zenywallet fixed.

**Review by zenywallet — APPROVED** [review]

**Review by zenywallet — APPROVED** [review]

**Pull request merged**
