### PR TITLE
BitZeny: Add a yescrypt cache to PeerLogicValidation::BlockChecked

### PR DESCRIPTION
**Pull request by ghost**
Fix missing cache in ```PeerLogicValidation::BlockChecked```.

### CODE REVIEW

**Comment by onokatio** [comment]
LGTM !

**Review by onokatio — COMMENTED** [review]
LGTM :+1:

**Comment by zenywallet** [comment]
Beautiful.

Why don't you implement hashdb in CBlockHeader? Exclude leveldb from primitives?

It takes a long time for the first time after upgrade from z1.2.1
We had better to consider the upgrade path. think it later.

**Review by zenywallet — COMMENTED** [review]
OK

**Review by hitobb — APPROVED** [review]

**Pull request merged**
