### PR TITLE
Add Discord Webhook notification

### PR DESCRIPTION
**Pull request by acid-chicken**
>### Discord invite link
>[https://discord.gg/xmWd3yy](https://discord.gg/xmWd3yy)

### CODE REVIEW

**Review by onokatio — DISMISSED** [review]

**Comment by acid-chicken** [comment]
Hmm, it didn't work. I'll resolve later.

**Review by ghost — CHANGES_REQUESTED** [review]
@acid-chicken ping

**Comment by acid-chicken** [comment]
@onokatio @shirako-jp It's now working successfully. Please re-review.
screen_shot

**Review by ghost — COMMENTED** [review]
LGTM
Squash commits before merge

**Comment by acid-chicken** [comment]
@shirako-jp OK, I squashed these commits.

**Review by onokatio — APPROVED** [review]

**Review by ghost — APPROVED** [review]
yay

**Pull request merged**
