### PR TITLE
[WIP] Hard Fork: ASIC/GPU resistant PoW

### PR DESCRIPTION
**Pull request by ghost**
TODO

### CODE REVIEW

**Comment by cryptozeny** [comment]
argon2dがbitzenyで動作しますか。 関心があります。応援します!

**Comment by cryptozeny** [comment]
応援します!

**Comment by solardiz** [comment]
I am biased (yescrypt author) and I am just a bystander here (not a user of BitZeny, am just curious), but as far as I'm aware Argon2 is more GPU friendly than yescrypt 0.5 at comparable memory usage, so this PR's title is inconsistent with its content. Argon2 includes cheap (with little synchronization overhead) 32x parallelism within one instance (plus quite some not-so-cheap parallelism above that), whereas yescrypt (with current settings) includes 4x of comparably cheap parallelism and 2x more (8x total, and that's the max) of not-so-cheap parallelism (which current yescrypt 0.5 GPU miners extracted anyway, despite of the overhead). So by switching to Argon2 you're making things 4x+ easier for GPUs in these terms alone (and there are more differences as well). Argon2 at up to at least tens of MB per instance is essentially limited by GPU memory bandwidth, which is generally much higher than what's available from a CPU (hundreds vs. tens of GB/s).

https://gitlab.com/omos/argon2-gpu is a decent implementation of Argon2 on GPU, but please disregard the outdated performance numbers cited in the README there (at this time) - actual performance was since improved to approach GPU memory bandwidth. From my e-mail exchange with the author, it reached e.g. nearly 70% of theoretical peak memory bandwidth on Titan X Maxwell and will probably get even closer to the theoretical peak on Pascal cards (GTX 10xx).

**Comment by cryptozeny** [comment]
@solardiz Thank you for commenting! Good to know! :smiley:

**Comment by hitobb** [comment]
@solardiz

Wow,I'm very happy to meet you!

All your suggestions are correct.
Argon 2's GPU resistant performance did not reach yescrypt 0.5 in our internal test.
Therefore, we are stopping adapt argon2 on 3.0.

So,I will close this PR without merging.

---

We are very interested in your new proposal:yespower 1.0

However,HF is not compatible with bitzeny.org software.
And the bitzeny.org's owner is missing.
bitcointalk's owner is missing too.

Therefore,We are planning to change to new coin name "BitZeny Plus" for HF.

When that time comes, we will publish the new name repository,new announce Twitter account,and new ANN.

Thank you!

**Comment by solardiz** [comment]
OK. Meanwhile, you may update to yespower in its yescrypt 0.5 compatibility mode (would be something like `.version = YESPOWER_0_5` in your source code), which will provide a few percent speedup due to implementation optimizations back-ported from yescrypt 1.0+. Your users can do so in their miners anyway, and it's probably best to provide those optimizations to the entire community, unless you consider the existing coin abandoned to the extent where this doesn't matter already.

**Comment by cryptozeny** [comment]
@solardiz thanks for great update! :smile: it makes cpuminer 3% ~ 15% faster! (average 7%) :heart: i have a question about `yespower-neon.c`. now i'm updating old cpuminer to yespower. is there a way to support old 32bit smartphones using `ARM NEON` like this?

https://github.com/macchky/cpuminer/blob/master/yescrypt-neon.c

**Comment by solardiz** [comment]
Yes, ARM NEON and Aarch64 ASIMD support is planned for a next version. Meanwhile, you can either drop it or keep your old yescrypt hack when building for NEON.

**Comment by cryptozeny** [comment]
@solardiz great news! can't wait 🤣

**Comment by cryptozeny** [comment]
@solardiz i tested yespower 0.5 on `aarch64` and it makes 10% faster with this option. :sweat_smile: 

```bash
./configure CFLAGS="-Ofast -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -ffast-math" CXXFLAGS="-Ofast -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -ffast-math"
```

aarch64 lscpu
```
$ lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
CPU max MHz:           1400.0000
CPU min MHz:           400.0000
```

**Comment by solardiz** [comment]
@cryptozeny 10% faster than what? And what compiler/version is this with?

**Comment by cryptozeny** [comment]
@solardiz cpuminer using `yesPower 0.5` on `aarch64`  is 10% faster than old `yesCrypt 0.5` on same machine. 

```
$ gcc --version
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609 
```

```
$ uname -a
Linux kirari 4.4.49-s5p6818 #1 SMP PREEMPT Fri Mar 23 15:29:14 HKT 2018 aarch64 aarch64 aarch64 GNU/Linux
```

i can give you more info :sweat_smile:

**Comment by cryptozeny** [comment]
old yescrypt `0.51 kH/s`
yespower 0.5 `0.57 kH/s`

i can share my code

**Comment by cryptozeny** [comment]
@solardiz 
its a test version `10%faster` branch and build with `build.sh`

**Comment by solardiz** [comment]
I merely asked you to clarify, which you did - thanks! I don't intend to look into this any further. My task remains to introduce SIMD code when I have time.

**Comment by cryptozeny** [comment]
sorry i didn't use `neon` option to this build. :sweat_smile: but it makes faster on aarch64. 

```
./autogen.sh && ./nomacro.pl && ./configure CFLAGS="-O3" && make
```

**Comment by cryptozeny** [comment]
Its fine :smiley: Thank you very much for giving us some good news! :+1:

**Comment by hitobb** [comment]
Discussion is finished.

argon2d does not have ASIC / GPU resistant than yescrypt 0.5.
yesPower 1.0 also does not have ASIC resistant than yescrypt 0.5.
yesPower 0.5 option also does not have ASIC resistant than yescrypt 0.5.


If bitzeny insists on "anti-GPU and ASIC", "Do not hard fork" is the best option.
If we change BitZeny's algorithm to yesPower 1.0, it should be the new coin name.
Because the concept is different like BTC and BCH.


So,I will close this PR without merging.
Thanks for the interesting results!

**Comment by solardiz** [comment]
I don't quite see how upgrading to yespower 1.0 changes the concept. Was moderate GPU friendliness part of the BitZeny concept? I think not. I think upgrading to yespower 1.0 will restore the GPU unfriendliness that was part of your original concept.

As to ASIC resistance, that's much harder. Probably future yespower (beyond 1.0) will provide some improvement in this respect (an early-reject feature allowing for much higher settings while not becoming more DoS'able; harder to implement in core and pools code, though). Meanwhile, I recommend yespower 1.0 settings of at least N=2048 r=32 (8 MiB, four times higher and slower than yours) to make use of VCU1525/BCU1525 FPGA boards (now popular for CryptoNight, etc. mining) more obviously not cost-effective. (Note that CryptoNight uses 2 MiB like you do now.)

So if you can't afford N=2048 r=32 (which cryply. uses with yespower 1.0 now), then you might in fact choose not to upgrade, so that GPU mining can stay more competitive than those FPGAs. If you can afford these settings, then I recommend upgrading.

**Comment by cryptozeny** [comment]
@solardiz thanks for great suggest! :smiley: 

I have a question,

```py
I recommend yespower 1.0 settings of at least N=2048 r=32 (8MB)
```

Does increasing the number increase gpu resistance? It can be a good settings? :thinking: 

 * a)
`N=2048 r=32 (8mb, original you said)`
 * b)
 `N=2048 r=64`
 * c)
 `N=4096 r=32`
 * d)
 `N=4096 r=64`

Are these possible options? More variations possible? :sweat_smile:

**Comment by solardiz** [comment]
With yespower 1.0, increasing N*r probably does *not* increase resistance against current GPUs, because they bump into another bottleneck first (before hitting their total memory size). It *might* increase resistance against future GPUs, but the range of values we're currently considering is likely not enough for that. So this is an OK safeguard to use, but it doesn't necessarily have an effect on GPU resistance now. Also `r=64` is unsupported (max `r` is now 32).

Increasing N*r forces FPGAs and ASICs to make relatively (more) use of off-die memory. GPUs have plenty of fast off-die memory anyway, but those other devices might not. OTOH, they might have more on-die memory. So a change from 2 MiB to 8 MiB does more against them than it possibly does against GPUs.

For yescrypt/yespower 0.5, increasing N*r *does* increase GPU resistance, including in this range (e.g. 2 MiB to 8 MiB or slightly higher). But changing the parameters in a hard-fork yet not switching to yespower 1.0 would be a weird thing for you to do.

**Comment by cryptozeny** [comment]
great to know! i have to learn more about yespower! :+1:

**Comment by hitobb** [comment]
I'm very happy to explain the road map of yesPower.
yesPower 1.0+ exceeds yescrypt!
At the technical point, your future is very nice.

As a marketing point, there is a neglected org, so compatibility with the oldest client is necessary. Therefore, the " bitzeny"coin's limit potencial is yesPower 0.5 option.

We should create a new coin forked from bitzeny and implement yesPower 1.0+. 
We will discuss it.

**Comment by hitobb** [comment]
Development was handed over to bitzenyPlus.

https://github.com/bitzenyPlus/BitZenyPlus/tree/feature/yespower-0.5

**Pull request closed without merging**
